### ISSUE TITLE
[inputs.exec] Error in plugin: metric parse error: expected field at 1:320

### ISSUE THREAD

**Issue by codemonkey6969** [stakeconomy/solanamonitoring#14]
Receiving this error ever since this morning. See screenshot attached.
Dec 01 00:03:01 NM-PROD-VALIDATOR1 telegraf[2234515]: 2022-12-01T00:03:01Z E! [inputs.exec] Error in plugin: metric parse error: expected field at 1:320: "nodemonitor,pubkey=FLVgaCPvSGFguumN9ao188izB4K4rxSWzkHneQMtkwQJ status=0,rootSlot=164169381,lastVote=164169412,leaderSlots=0,skippedSlots=0,pctSkipped=0,pctTotSk>
~
![image](https://user-images.githubusercontent.com/67477461/204934894-17154e1d-d03b-4ced-ba3c-2c2d1abf5d5e.png)

**Comment by DataKnox** [comment]
Also receiving a similar error
`Error in plugin: metric parse error: expected field at 1:328: "nodemonitor,pubkey=juigBT2qetpYpf1iwgjaiWTjryKkY3uUTVAnRFKkqY6 status=0,rootSlot=167056276,lastVote=167056307,leaderSlots=200,skippedSlots=44,pctSkipped=22.00,pctTotSkipped=4.29,pctSkippedDelta=412.82,pctTotDelinquent=1.67,version=11410,pctNewerVersions=60.13,commission=0,activatedStake=224678.16,credits=24180256,solanaPrice=null,openFiles=471840,validatorBalance=24.02827182,validatorVoteBalance=1.012147976,nodes=2001,epoch=386,pctEpochElapsed=70.45,validatorCreditsCurrent=206032,validatorCreditsCurrent=206032,epochEnds=1671147060000,pctVote=67.6900,tps=124141750093 1671124500104245785"`

**Comment by DataKnox** [comment]
Resolved in #15

**Comment by DataKnox** [comment]
Ok to close this ticket
