### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by ghost** [stakeconomy/solanamonitoring#18]
After setting up I only see like 5% of data of all the visualizations on the dashboard. And none of them were related to Solana chain state information.

**Comment by Jomossey** [comment]
@swedeape100 Have you checked the settings or filters to ensure everything is correctly configured for the visualizations to display the right data? Double-checking those settings might help you see the complete information you're looking for.

**Comment by Jomossey** [comment]
@swedeape100 Check the configuration settings on the Solana validator node to ensure that it's set up to collect and provide the chain state information. Once the node is properly configured, the dashboard should start showing the relevant Solana chain data.
