### ISSUE TITLE
[inputs.exec] Error

### ISSUE THREAD

**Issue by happystake** [stakeconomy/solanamonitoring#6]
Hi all!
After installing and correcting the configuration file, when starting the telegraph service, such an error appears, please tell me how to fix it
telegraf[24046]: 2021-05-31T10:38:00Z E! [inputs.exec] Error in plugin: exec: exit status 1 for command 'sudo su -c /home/sol/solanamonitoring/monitor.sh -s /bin/bash sol': Error: No such file or directory (os error 2)

**Comment by stakeconomy** [comment]
Please check the user and path. something is not correct
